skip_tags: true

version: 2.0.{build}

image: 
  - Visual Studio 2022
  - Ubuntu2004

environment:
  github_access_token:
    secure: EMJUnvkJwGXaFnohUmpxqyNd0R4hpMCeUtl5aVtHqFerhd0UdYc+lTJV3H3sIhg6
  github_email:
    secure: B5VQnP9LQP9stxxvu2G/3MCKhVySoSVf/mvyqHY5K8M=

init:
  - git config --global core.autocrlf input
  - sh: |
      apt-get update \
      && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      ca-certificates \
      \
      # .NET Core dependencies
      libc6 \
      libgcc1 \
      libgssapi-krb5-2 \
      libicu66 \
      libssl1.1 \
      libstdc++6 \
      zlib1g \
      && rm -rf /var/lib/apt/lists/*
  - sh sudo snap install dotnet-sdk --channel=8.0/beta --classic
  - sh sudo snap alias dotnet-sdk.dotnet dotnet
  

build_script:
  - dotnet tool restore
  - dotnet nake pack

artifacts:
  - path: Artifacts\Release\*.nupkg